backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/products" # Where product images will be stored
public_folder: "/src/assets/products"

collections:
  - name: "products"
    label: "Products"
    folder: "src/data/products"
    create: true
    slug: "{{category}}-{{slug}}"
    fields:
      - { label: "Product Name", name: "name", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Category", name: "category", widget: "select", options: ["Nuts", "Seeds", "Peanuts", "Snacks & Crackers"] }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }

  - name: "offers"
    label: "Special Offers"
    folder: "src/data/offers"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Offer Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Discount Percentage", name: "discount", widget: "number", required: false }
      - { label: "Start Date", name: "startDate", widget: "datetime" }
      - { label: "End Date", name: "endDate", widget: "datetime" }
      - { label: "Active", name: "active", widget: "boolean", default: true }
      - { label: "Banner Image", name: "banner", widget: "image", required: false }

  - name: "settings"
    label: "Site Settings"
    files:
      - label: "Contact Information"
        name: "contact"
        file: "src/data/settings/contact.json"
        fields:
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "WhatsApp Number", name: "whatsapp", widget: "string" }
          - { label: "Address", name: "address", widget: "text" }
